import type { Metadata } from "next";
import { Cinzel } from "next/font/google";
import "@/app/styles/global.css";
import Header from "@/components/Header/Header";

const cinzel = Cinzel({
  variable: "--font-cinzel-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
